; PlatformIO Project Configuration File

[common]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600 

; --- 1. 调频率实验 ---
[env:test_freq]
extends = common
; 逻辑：先踢出所有(-<*>)，再专门拉入这一个(+<...>)
build_src_filter = -<*> +<experiment.cpp>

; --- 2. 正反转一圈 ---
[env:one_circle]
extends = common
build_src_filter = -<*> +<auto_circle.cpp>

; --- 3. 一直转模式 ---
[env:always_run]
extends = common
build_src_filter = -<*> +<mode_run.cpp>

; --- 4. 固定圈数实验 ---
[env:fixed_circles]
extends = common
build_src_filter = -<*> +<fixed_circles.cpp>

; --- 5. 固定时间实验 ---
[env:fixed_time]
extends = common
build_src_filter = -<*> +<fixed_time.cpp>