; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[common]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600 

[env:test_freq]
extends = common
; 包含所有，排除 auto_circle.cpp
build_src_filter = +<*> -<auto_circle.cpp>

[env:one_circle]
extends = common
; 包含所有，排除 experiment.cpp
build_src_filter = +<*> -<experiment.cpp>

; --- 环境3：一直转模式 ---
[env:always_run]
extends = common
; 包含所有，排除“串口实验”和“转一圈”
build_src_filter = +<*> -<experiment.cpp> -<auto_circle.cpp>